
### Taxa de Abandono Ensino Médio
GET http://dados.fee.tche.br/ckan-download/fee-2013-mun-taxa-de-abandono-estadual-102590.csv

###
GET https://ifrs.edu.br/riogrande/retificacao-da-2a-chamada-do-curso-tecnico-em-automacao-industrial-enem/

###

GET http://www.heroisdateve.com.br/wp-content/uploads/2018/02/DU-LvQGW4AIK6sn.jpg
